### ISSUE TITLE
一番上のブロックが消えるバグ

### ISSUE THREAD

**Issue by Acha0203** [CS-MokuMoku-Team-4/drop-numbers-game#1]
ブロックを落とす位置を変更すると、一番上に積み上げられたブロックが消えることがある。

**Comment by SouthernMinami** [comment]
https://github.com/CS-MokuMoku-Team-4/drop-numbers-game/assets/81604492/57655ba1-8ac5-4a00-8c6d-0072578364b8

遊んでたらそれらしいバグを見つけたのですが、もしかしてこのissueのバグがこれでしょうか？（うまく動画貼れてなかったらすみません🙏）

発生条件
1. デフォルトでブロックが降ってくる列が一番高く積み上がってる列ではないこと
2. 降ってくるブロックが一番高いブロックの一段上まで来たタイミングで、一番高くブロックが積み上がってる列をクリックすること

**Comment by Acha0203** [comment]
これです!! 発生条件を探ってくださってありがとうございます!!!
お陰様で、原因を解明できそうな気がしてきました😆
